#!/bin/bash

ENCODED_MEETINGS_FILE="$(dirname $BASH_SOURCE)/.meetings.encoded"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
mkdir -p "$XDG_CONFIG_HOME/classie"

if [ "$1" == "--help" ] || [ $# == 0 ]; then
    echo -e "Usage: classie MEETING_NAME [zw]"
    echo -e "    MEETING_NAME: The name of the meeting to join, as defined in the ~/.meetings file."
    echo -e "    zw: Optional argument to open Zoom meetings in the web browser instead of the Zoom app."
    exit 0
elif [ "$1" == "--hucs" ]; then
    base64 -d < "$ENCODED_MEETINGS_FILE" > "$XDG_CONFIG_HOME/classie/.meetings"
    exit 0
fi

OS="$(uname)"

HAS_APP=0
case "$OS" in
    "Linux")
        if command -v zoom > /dev/null; then
            HAS_APP=1
        fi

        RUN_COMMAND="xdg-open"
        ;;
    "Darwin")
        if [ -d "/Applications/Zoom.app" ]; then
            HAS_APP=1
        fi

        # Zoom does not seem to work well in Safari, try other browsers first.
        PREFERRED_BROWSER="${PREFERRED_BROWSER:-Firefox}"
        if [ ! -d "/Applications/$PREFERRED_BROWSER.app" ]; then
            PREFERRED_BROWSER="Google Chrome"
        fi
        if [ ! -d "/Applications/$PREFERRED_BROWSER.app" ]; then
            PREFERRED_BROWSER="Safari"
        fi

        RUN_COMMAND="open -a $PREFERRED_BROWSER"
        ;;
    *)
        echo "Unsupported OS: $OS"
        exit 1
        ;;
esac

if [ ! -f "$XDG_CONFIG_HOME/classie/.meetings" ]; then
    base64 -d < "$ENCODED_MEETINGS_FILE" > "$XDG_CONFIG_HOME/classie/.meetings"
fi

meeting_name="$1"
meeting_url="$(grep -i "^$meeting_name" "$XDG_CONFIG_HOME/classie/.meetings" | cut -d' ' -f2)"

if [ -z "$meeting_url" ]; then
    echo "Error: Meeting name "$meeting_name" not found in .meetings file"
elif [ "$2" == "zw" ] || [ $HAS_APP == 0 ]; then
    meeting_url="$(echo "$meeting_url" | sed 's|j/|wc/join/|g')"
    $RUN_COMMAND "$meeting_url"
else
    $RUN_COMMAND "$meeting_url"
fi
