#!/bin/bash

ENCODED_MEETINGS_FILE="$(dirname $BASH_SOURCE)/meetings.base64"
XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
MEETINGS_FILE="$XDG_CONFIG_HOME/classie/meetings"
mkdir -p "$XDG_CONFIG_HOME/classie"

if [ "$1" == "--help" ] || [ $# == 0 ]; then
    echo -e "Usage: classie MEETING_NAME [zw]"
    echo -e "    MEETING_NAME: The name of the meeting to join, as defined in the ~/.meetings file."
    echo -e "    zw: Optional argument to open Zoom meetings in the web browser instead of the Zoom app."
    exit 0
elif [ "$1" == "--hucs" ]; then
    base64 -d < "$ENCODED_MEETINGS_FILE" > "$MEETINGS_FILE"
    exit 0
elif [ "$1" == "--init" ]; then
    touch "$MEETINGS_FILE"
    echo "meetings file has been created at "$MEETINGS_FILE""
    exit 0
fi

OS="$(uname)"

HAS_APP=0
case "$OS" in
    "Linux")
        if [ ! -z $(xdg-mime query default x-scheme-handler/zoommtg 2> /dev/null) ]; then
            HAS_APP=1
        fi

        RUN_COMMAND="xdg-open"
        ;;
    "Darwin")
        if [ -d "/Applications/Zoom.app" ]; then
            HAS_APP=1
        fi

        # Zoom does not seem to work well in Safari, try other browsers first.
        PREFERRED_BROWSER="${PREFERRED_BROWSER:-Firefox}"
        if [ ! -d "/Applications/$PREFERRED_BROWSER.app" ]; then
            PREFERRED_BROWSER="Google Chrome"
        fi
        if [ ! -d "/Applications/$PREFERRED_BROWSER.app" ]; then
            PREFERRED_BROWSER="Safari"
        fi

        RUN_COMMAND="open -a $PREFERRED_BROWSER"
        ;;
    *)
        echo "Unsupported OS: $OS"
        exit 1
        ;;
esac

if [ ! -f "$MEETINGS_FILE" ]; then
    base64 -d < "$ENCODED_MEETINGS_FILE" > "$MEETINGS_FILE"
fi

meeting_name="$1"
meeting_url="$(grep -i "^$meeting_name" "$MEETINGS_FILE" | cut -d' ' -f2)"

https_to_zoommtg() {
    # $1 = https url
    # Prints the meeting url in zoommtg scheme if $1 belongs to a Zoom meeting, otherwise prints the input as is.
    perl -ne '/http[s]?:\/\/[A-Za-z0-9\-]*[\.]?zoom\.us\/j\/([0-9]+)(?:(?=\?pwd=)\?pwd=([A-Za-z0-9\.\-\_]+)&?)?/ ? print "zoommtg://zoom.us/join?action=join&confno=$1&pwd=$2\n" : print $_' <<< $1
}

if [ -z "$meeting_url" ]; then
    echo "Error: Meeting name "$meeting_name" not found in .meetings file"
elif [ "$2" == "zw" ] || [ $HAS_APP == 0 ]; then
    meeting_url="$(echo "$meeting_url" | sed 's|j/|wc/join/|g')"
    $RUN_COMMAND "$meeting_url"
else
    # If we're working with a Zoom url, convert it into the zoommtg url scheme
    meeting_url=$(https_to_zoommtg $meeting_url)

    $RUN_COMMAND "$meeting_url"
fi
